name: senior_sos
description: "SASEhack Fall 2024"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_native_contact_picker: ^0.0.8
  flutter_sms:
    path: assets/flutter_sms-master
  geolocator: ^13.0.1
  permission_handler: ^11.3.1
  porcupine_flutter: ^3.0.3
  shared_preferences: ^2.3.2
  torch_light: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/I-can--t-get-up_en_android_v3_0_0.ppn
    - assets/I-can--t-get-up_en_ios_v3_0_0.ppn
    - assets/activated.png
    - assets/listening.png
    - assets/off.png